/**
 * Prune QA / load-test residue from the FleexBid database.
 *
 * WHY: automated verification runs (scripts/e2e-verify.mjs, loadtest.mjs,
 * phase*-verify.mjs, concurrency-verify.mjs, ...) create transporters,
 * requirements and bids against whatever DATABASE_URL points at - including
 * production. That left ~120 `load.09e963.*` carrier rows, dozens of
 * `@fleexbid.test` QA accounts and soft-deleted test auctions inflating every
 * list query and scan.
 *
 * SAFETY MODEL
 *   - DRY RUN by default: prints exactly what it would change and exits 0.
 *   - Pass --apply to actually write.
 *   - Only rows matching an explicit test-data pattern are considered. Real
 *     company accounts (e.g. *@gmail.com, *@sundaramalloys.com) are NEVER
 *     touched, even when they look like fixtures.
 *   - Business data is SOFT-deleted (is_deleted = TRUE) rather than physically
 *     removed, matching the platform's own soft-delete-only policy. The change
 *     is therefore reversible with a one-line UPDATE.
 *   - Rows that are ALREADY soft-deleted are only reported (they are invisible
 *     to users already); use --report-deleted-only to see them without any
 *     writes being proposed.
 *
 * Usage:
 *   node scripts/cleanup-qa-data.mjs                     # dry run
 *   node scripts/cleanup-qa-data.mjs --apply             # soft-delete test rows
 *   node scripts/cleanup-qa-data.mjs --apply --yes-really
 */
import pg from 'pg';
import dotenv from 'dotenv';

dotenv.config({ path: '.env.local' });

const args = process.argv.slice(2);
const apply = args.includes('--apply');
const confirmed = args.includes('--yes-really');

// Explicit test-data fingerprints. Deliberately narrow: only synthetic domains
// and the ID prefixes generated by the verification scripts.
const TEST_EMAIL_PATTERN = '%@fleexbid.test';
const TEST_EMAIL_PATTERN_2 = '%@example.com';

// The verification scripts create requirements with placeholder locations and
// material (P2 -> D2, material M2, vehicle TRAILER). Requiring the pickup AND
// delivery placeholders TOGETHER is deliberately strict: matching either one
// alone risked catching a real shipment whose location happened to be a short
// code.
const QA_REQUIREMENT_PREDICATE = `
  is_deleted = FALSE
  AND pickup_location IN ('P2', 'P1', 'P3')
  AND delivery_location IN ('D2', 'D1', 'D3')
  AND material IN ('M2', 'M1', 'M3')
`;
// Same fingerprint without the is_deleted filter, for reporting counts.
const QA_REQUIREMENT_FINGERPRINT = `
  pickup_location IN ('P2', 'P1', 'P3')
  AND delivery_location IN ('D2', 'D1', 'D3')
  AND material IN ('M2', 'M1', 'M3')
`;

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error('[cleanup-qa-data] FATAL: DATABASE_URL is not set (checked .env.local).');
  process.exit(1);
}

const masked = connectionString.replace(/:\/\/([^:]+):[^@]*@/, '://$1:***@');
console.log(`[cleanup-qa-data] target DB: ${masked}`);
console.log(`[cleanup-qa-data] mode:      ${apply ? 'APPLY (will write)' : 'DRY RUN (no writes)'}\n`);

if (apply && !confirmed) {
  console.error(
    '[cleanup-qa-data] Refusing to write without --yes-really.\n' +
      '  This soft-deletes rows in the database above. Run without --apply first\n' +
      '  to review the exact counts.'
  );
  process.exit(1);
}

const needsSsl = connectionString.includes('neon.tech') || connectionString.includes('sslmode=require');
const pool = new pg.Pool({ connectionString, ssl: needsSsl ? { rejectUnauthorized: false } : false });

const TABLES = [
  { table: 'transporters', emailCol: 'email' },
  { table: 'requirements', emailCol: null },
];

try {
  console.log('=== synthetic accounts (by email domain) ===');
  for (const { table, emailCol } of TABLES) {
    if (!emailCol) continue;
    const q = await pool.query(
      `SELECT
         count(*) FILTER (WHERE is_deleted = FALSE)::int AS live,
         count(*) FILTER (WHERE is_deleted = TRUE)::int  AS already_deleted
       FROM ${table}
       WHERE lower(${emailCol}) LIKE $1 OR lower(${emailCol}) LIKE $2`,
      [TEST_EMAIL_PATTERN, TEST_EMAIL_PATTERN_2]
    );
    const { live, already_deleted } = q.rows[0];
    console.log(`  ${table.padEnd(14)} live=${String(live).padStart(4)}  already soft-deleted=${already_deleted}`);
  }

  console.log('\n=== synthetic requirements (placeholder route fingerprint) ===');
  const reqs = await pool.query(
    `SELECT
       count(*) FILTER (WHERE is_deleted = FALSE)::int AS live,
       count(*) FILTER (WHERE is_deleted = TRUE)::int  AS already_deleted
     FROM requirements
     WHERE ${QA_REQUIREMENT_FINGERPRINT}`
  );
  console.log(`  requirements   live=${reqs.rows[0].live}  already soft-deleted=${reqs.rows[0].already_deleted}`);

  console.log('\n=== orphaned bids on soft-deleted requirements ===');
  const orphanBids = await pool.query(
    `SELECT count(*)::int AS c
     FROM bids b
     JOIN requirements r ON r.id = b.requirement_id
     WHERE r.is_deleted = TRUE`
  );
  console.log(`  bids belonging to soft-deleted auctions: ${orphanBids.rows[0].c}  (left untouched - see note below)`);

  console.log('\n=== visible (live) account roster after cleanup ===');
  const liveAccounts = await pool.query(
    `SELECT count(*)::int AS c FROM transporters
     WHERE is_deleted = FALSE
       AND lower(email) NOT LIKE $1 AND lower(email) NOT LIKE $2`,
    [TEST_EMAIL_PATTERN, TEST_EMAIL_PATTERN_2]
  );
  console.log(`  transporters that would remain: ${liveAccounts.rows[0].c}`);

  if (!apply) {
    console.log('\n[cleanup-qa-data] DRY RUN complete. Re-run with --apply --yes-really to soft-delete the');
    console.log('                  synthetic transporter and requirement rows listed above.');
    console.log('[cleanup-qa-data] Bids are deliberately NOT deleted: they are immutable bid-history');
    console.log('                  records and their parent auctions are already hidden from users.');
  } else {
    const t = await pool.query(
      `UPDATE transporters SET is_deleted = TRUE
       WHERE is_deleted = FALSE AND (lower(email) LIKE $1 OR lower(email) LIKE $2)`,
      [TEST_EMAIL_PATTERN, TEST_EMAIL_PATTERN_2]
    );
    const r = await pool.query(
      `UPDATE requirements SET is_deleted = TRUE WHERE ${QA_REQUIREMENT_PREDICATE}`
    );
    console.log(`\n[cleanup-qa-data] APPLIED: soft-deleted ${t.rowCount} transporter(s), ${r.rowCount} requirement(s).`);
    console.log('[cleanup-qa-data] To revert: UPDATE <table> SET is_deleted = FALSE WHERE id IN (...);');
  }
} catch (error) {
  console.error('[cleanup-qa-data] FAILED:', error.message);
  process.exit(1);
} finally {
  await pool.end();
}
